### PR TITLE
Add Chapter 15: Firmata implementation for the Pharo Programming Language

### PR DESCRIPTION
**Pull request by huyhoang8398**
#### Description

Create post on Firmata implementation for the Pharo Programming Language

#### Checklist

- [x] considerate and respectful language.
- [ ] author name (and meta data file if possible).

Reference:  https://github.com/pharo-iot/Firmata
Special thank to  @dionisiydk @guillep for implementing Firmata on Pharo

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Thank you Hoang for your work !
Normally there is a support for Firmata with PharoThings, did you investigate this ?

**Comment by huyhoang8398** [comment]
There is branch which provides same kind of inspector for arduino models 
https://github.com/pharo-iot/PharoThings/tree/arduinoBoards. 

Also notice that firmata requires serial port plugin which does not work on Mac VM. As I know it only works with Linux

**Comment by SergeStinckwich** [comment]
The serial port was working at one point on MacOS. I didn't test recently.

Maybe @oliveiraallex can clarify the situation about arduinoBoards branch and Firmata support under PharoThings.

**Comment by dionisiydk** [comment]
I remember that I merged it. So it should be in the master or dev

вт, 5 нояб. 2019 г., 15:22 Do Hoang <notifications@github.com>:

**Comment by SergeStinckwich** [comment]
ok maybe you could remove the branch if merged.

**Comment by huyhoang8398** [comment]
So this PR is able be merged or we need to make more instructions about Firmata and Arduino on Pharo?

**Comment by SergeStinckwich** [comment]
The book is about PharoThings so I can guess you need to explain a little bit how to use Firmata in conjonction with PharoThings.

**Comment by dionisiydk** [comment]
> ok maybe you could remove the branch if merged.

done

**Comment by dionisiydk** [comment]
> Special thank to @dionisiydk for implementing Firmata on Pharo

It was implemented by @guillep (or he knows better the author). I only migrated it under pharo-iot umbrella

**Comment by SergeStinckwich** [comment]
@huyhoang8398 can you add more information on how to use Firmata with PharoThings?
Maybe we can rename the chapter as "PharoThings on Arduino" ?
@oliveiraallex can we commit this PR ?

**Comment by huyhoang8398** [comment]
@SergeStinckwich  Yes, i will add more commits

**Comment by oliveiraallex** [comment]
> @oliveiraallex can we commit this PR ?

Yes, I'm going to merge it.

Thanks @huyhoang8398!

**Pull request merged**
